
spring.profiles.active: prod

server.port: 8888

logging.file.name: 'log/klik.log'
logging.file.max-size: 10MB
logging.file.max-history: 7
logging.level.root: info

cron.minutes.ten: 0 0/10 * * * ?

slack.authorization:
slack.user:
slack.channel:

cookie.konzum:



